### ISSUE TITLE
[Feature request] Emotes in calendar

### ISSUE THREAD

**Issue by el97** [randomBrainstormer/MMM-GoogleCalendar#73]
Hi! I use the calendar together with my family. Some of them use emotes in the title of the event. Sadly it only renders as a box in the text. Is it possible to render the emotes as well?

**Comment by bagstoper** [comment]
Emoji are handled by fonts you should be able to install a font to magicmirror that has emoji support. ***I have not attempted this just an assumtion based on my knowledge of fonts.

Go to the fonts folder.
Then `npm install` the appropriate package

https://fontawesome.com/docs/web/setup/packages

Then change the font in the top of css/custom.css

```css
.normal,
.dimmed,
header,
body {
  color: #fff;
  font-family: "Times New Roman", "Fallback_font_or_font_family"
}
```
